# Generated by Django 5.2.7 on 2026-03-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dream_team_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
