import api from './client'

export const getPlayers = (params) => api.get('/fpl/players/', { params })
export const getPlayer = (fplId) => api.get(`/fpl/players/${fplId}/`)
export const getPlayerHistory = (fplId) => api.get(`/fpl/players/${fplId}/history/`)
export const getTeams = () => api.get('/fpl/teams/')
export const getGameweeks = () => api.get('/fpl/gameweeks/')
export const getCurrentGw = () => api.get('/fpl/gameweeks/current/')
export const getFixtures = (params) => api.get('/fpl/fixtures/', { params })

export const getBestPicks       = (params)        => api.get('/predictions/best-picks/',       { params })
export const getBestTeam        = ()              => api.get('/predictions/best-team/')
export const getTrackRecord     = (n = 3)         => api.get('/predictions/track-record/',     { params: { n } })
export const getGwDetail        = (gw)            => api.get('/predictions/track-record/',     { params: { gw } })
export const getGwHistory       = ()              => api.get('/predictions/gw-history/')
export const getPredictions     = (params)        => api.get('/predictions/',                  { params })
export const predictPlayer      = (fplId)         => api.get(`/predictions/player/${fplId}/`)
export const getDifferentials   = ()              => api.get('/predictions/differentials/')
export const getCommunityCompare = ()             => api.get('/predictions/community-compare/')

export const getSquad = () => api.get('/manager/squad/current/')
export const syncSquad = () => api.post('/manager/squad/sync/')
export const getDashboard = () => api.get('/manager/dashboard/')
export const getTransfers = () => api.get('/manager/transfers/')
export const generateTransfers = () => api.post('/manager/transfers/')
export const acceptTransfer = (id, accepted) => api.patch(`/manager/transfers/${id}/accept/`, { accepted })
export const getCaptain = () => api.get('/manager/captain/')
export const generateCaptain = () => api.post('/manager/captain/')
export const getChips = () => api.get('/manager/chips/')
export const getAdvice = () => api.get('/manager/advice/')
export const postAdvice = (payload) => api.post('/manager/advice/', payload)

export const changePassword = (data) => api.post('/auth/change-password/', data)
export const getFplManager = (teamId) => api.get(`/fpl/manager/${teamId}/`)

export const register = (data) => api.post('/auth/register/', data)
export const login = (data) => api.post('/auth/login/', data)
export const logout = (refresh) => api.post('/auth/logout/', { refresh })
export const getProfile = () => api.get('/auth/profile/')
export const updateProfile = (data) => api.patch('/auth/profile/', data)
