# Generated by Django 5.2.7 on 2026-03-04 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fpl', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.FloatField(default=0.0, help_text='Money in bank (£m)')),
                ('free_transfers', models.PositiveSmallIntegerField(default=1)),
                ('overall_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('gameweek_points', models.IntegerField(blank=True, null=True)),
                ('total_points', models.IntegerField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='fpl.gameweek')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-gameweek__fpl_id'],
                'unique_together': {('user', 'gameweek')},
            },
        ),
        migrations.CreateModel(
            name='TransferSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_gain', models.FloatField(help_text='Estimated points gain over next GW')),
                ('reason', models.CharField(choices=[('form', 'In Form'), ('fixture', 'Good Fixtures'), ('injury', 'Injury Replacement'), ('price_rise', 'Price Rise'), ('differential', 'Differential Pick'), ('prediction', 'High Predicted Points')], max_length=20)),
                ('reason_detail', models.TextField(blank=True)),
                ('cost_impact', models.FloatField(default=0.0, help_text='Positive = profit, negative = loss in bank')),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fpl.gameweek')),
                ('player_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_in', to='fpl.player')),
                ('player_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_out', to='fpl.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-points_gain'],
            },
        ),
        migrations.CreateModel(
            name='CaptainSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain_predicted', models.FloatField()),
                ('vc_predicted', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain_picks', to='fpl.player')),
                ('differential_captain', models.ForeignKey(blank=True, help_text='Low-ownership high-upside alternative', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='differential_captain_picks', to='fpl.player')),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fpl.gameweek')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain_suggestions', to=settings.AUTH_USER_MODEL)),
                ('vice_captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vc_picks', to='fpl.player')),
            ],
            options={
                'unique_together': {('user', 'gameweek')},
            },
        ),
        migrations.CreateModel(
            name='ChipAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip', models.CharField(choices=[('wildcard', 'Wildcard'), ('freehit', 'Free Hit'), ('benchboost', 'Bench Boost'), ('triplecaptain', 'Triple Captain')], max_length=20)),
                ('recommended', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0, help_text='0-10 confidence score')),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fpl.gameweek')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chip_advice', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'gameweek', 'chip')},
            },
        ),
        migrations.CreateModel(
            name='SquadPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_captain', models.BooleanField(default=False)),
                ('is_vice_captain', models.BooleanField(default=False)),
                ('is_starter', models.BooleanField(default=True)),
                ('bench_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('purchase_price', models.PositiveIntegerField(default=0, help_text='Price when bought (10x)')),
                ('selling_price', models.PositiveIntegerField(default=0, help_text='Current sell price (10x)')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fpl.player')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='manager.squad')),
            ],
            options={
                'unique_together': {('squad', 'player')},
            },
        ),
    ]
